### ISSUE TITLE
Secrets.yml

### ISSUE THREAD

**Issue by morenoh149** [patrickod/noisebridge-donate#1]
Could the secrets be better off in environment variables?
Is this binary vulnerable to a brute-force attack?

**Comment by patrickod** [comment]
Production ones will be in environment variables. At the moment it only contains keys for Stripe in test mode + development secret key for sessions. 

The `secrets.yml` file is encrypted using https://github.com/AGWA/git-crypt, I'm pretty happy with it for the moment.
