### ISSUE TITLE
Make it responsive

### ISSUE THREAD

**Issue by patrickod** [patrickod/noisebridge-donate#26]
Currently the site doesn't work well on mobile devices. It should collapse into a single column linear layout and the form should be optimized for smaller screens. 

Also on certain iOS versions the credit card form inputs break completely, specifically 3 horizontally grouped fields for expiration date & CVC

**Comment by morenoh149** [comment]
I can do this if you want

**Comment by patrickod** [comment]
if you'd like to give it a shot that'd be great. the bootstrap CSS makes
this easy.

**Comment by morenoh149** [comment]
I see some attempts to use flexbox. Would you prefer the use of flexbox or bootstrap columns throughout? @patrickod

**Comment by patrickod** [comment]
I think that flexbox is likely the better bet here. It has really wide browser support and it makes life with CSS much much easier http://caniuse.com/#search=flexbox

That + media query styles for reordering content at certain screen sizes should be a winning combination

**Comment by patrickod** [comment]
@morenoh149 the best practice here is to write the stylesheets with the non vendor prefixed styles, and then use [autoprefixer](https://github.com/ai/autoprefixer-rails) to automatically add in the vendor specific prefixes in the asset pipeline

**Comment by patrickod** [comment]
Fixed by https://github.com/patrickod/noisebridge-donate/pull/31
